title: Addressables Wizard
description: The ultimate professional suite for Unity Addressables management.
remote_theme: just-the-docs/just-the-docs

# URL Settings
url: "https://decnet-games.github.io"
baseurl: "/ADDRESSABLES_WIZARD_DOC"

# Navigation Settings
nav_config:
  fixed_nav: true

# Footer Settings
footer_content: "© 2026 DecNet. Professional Unity Assets."

# Color Scheme
color_scheme: dark
